### ISSUE TITLE
注入失败 咋回事

### ISSUE THREAD

**Issue by Jerry1ee** [jukylin/istio-ui#2]
failed to convert to proto. unknown field "policyCheckFailOpen" in v1alpha1.MeshConfig

**Comment by jukylin** [comment]
"policyCheckFailOpen" 是什么配置？

**Comment by Jerry1ee** [comment]
不知道，我是直接部署的istio官方的那个book info的例子，然后点注入就提示这个，还有我的istio-sidecar-injector在running ，tag也改了，部署的时候不应该就直接自动注入了吗

**Comment by jukylin** [comment]
你部署哪个版本？

**Comment by Jerry1ee** [comment]
istio 1.0.5

**Comment by jukylin** [comment]
你试一下1.0.0版本

**Comment by Jerry1ee** [comment]
您好，我刚才手工注入了一次，注入成功了，但还是不太清楚没能自动注入。。。

**Comment by Jerry1ee** [comment]
还想请问一下您的模板功能是打算具体实现怎样的功能？

**Comment by jukylin** [comment]
你可以去看一下小米开源 的[naftis](https://github.com/XiaoMi/naftis)
